### ISSUE TITLE
La clase IEstadoSolicitudDeServicioTecnico

### ISSUE THREAD

**Issue by ExequielNeuquen** [Estudiantina/Estudiantina#5]
La clase IEstadoSolicitudDeServicioTecnico debe de hacer la transferencia entre los estados. Fijate eso. Asi como lo tenes esta mal

**Comment by matiasnahuelheredia** [comment]
genial tus contribuciones como decís que lo haga Exequiel ? en tu proyecto lo tienen de forma correcta?

**Comment by ExequielNeuquen** [comment]
Asi se hace
public interface IEstado {
void asignarTecnico(final Tecnico tecnico);
void solicitarInsumos(final int cantidad, final String producto,
final String marca, final String modelo);
void finalizarSoporte() throws EncriptaException;
void asignarNuevoEquipo(
final @Named("Nombre de Equipo") String rotulo,
final @Named("IP") String ip,
final @Named("MAC") String mac,
final @Named("HDD Marca ") String marcaDisco,
final @Named("HDD Categoria ") CategoriaDisco tipoDisco,
final @Named("HDD Tamaño ") int tamanoDisco,
final @Named("CPU Modelo ") String modeloProcesador,
final @Named("RAM Modelo") String modeloRam,
final @Named("RAM Tamaño") int tamanoRam,
final @Named("RAM Marca") String marcaRam,
final @Named("Modelo Motherboard") String modeloMotherboard,
final @Named("Fabricante") String fabricante,
final @Optional @Named("Monitor") Monitor monitor,
final @Optional @Named("Impresora") Impresora impresora,
final @Optional @Named("Software") Software sotfware);
boolean escondeAsignarTecnico();
boolean escondeFinalizarSoporte();
boolean escondeSolicitarInsumos();
boolean escondeLlegaronInsumos();
boolean escondeNoHayInsumos();
boolean escondeAsignarNuevoEquipo();
}
