### ISSUE TITLE
Diagrama de Estado

### ISSUE THREAD

**Issue by ExequielNeuquen** [Estudiantina/Estudiantina#7]
En el Diagrama de estado. Te falta poner la variables de cambio de estados. Fijate eso, asi como tenes el diagrama esta incompleto.

**Comment by matiasnahuelheredia** [comment]
te referís a los métodos que hacen que cambie de estado ¿no? si se los tengo que colocar gracias por tu aporte exe

**Comment by ExequielNeuquen** [comment]
Si, lo métodos que hacen que cambien de estados.

**Comment by matiasnahuelheredia** [comment]
genial ;)
